//
//  UnicodeRange.swift
//  CoreFont
//
//  Created by Mark Douma on 1/29/2026.
//

import Foundation

public extension FontTable_OS2 {

    struct UnicodeRange: OptionSet {
        public let rawValue: Int
        public init(rawValue: Int) {
            self.rawValue = rawValue
        }

        public static let basicLatin:                              UnicodeRange = .init(rawValue: 0)
        public static let latin1Supplement:                        UnicodeRange = .init(rawValue: 1)
        public static let latinExtendedA:                          UnicodeRange = .init(rawValue: 2)
        public static let latinExtendedB:                          UnicodeRange = .init(rawValue: 3)
        public static let ipaPhoneticExtensions:                   UnicodeRange = .init(rawValue: 4)
        public static let spacingModifierLetters:                  UnicodeRange = .init(rawValue: 5)
        public static let combiningDiacriticalMarks:               UnicodeRange = .init(rawValue: 6)
        public static let greekAndCoptic:                          UnicodeRange = .init(rawValue: 7)
        public static let coptic:                                  UnicodeRange = .init(rawValue: 8)
        public static let cyrillic:                                UnicodeRange = .init(rawValue: 9)
        public static let armenian:                                UnicodeRange = .init(rawValue: 10)
        public static let hebrew:                                  UnicodeRange = .init(rawValue: 11)
        public static let vai:                                     UnicodeRange = .init(rawValue: 12)
        public static let arabic:                                  UnicodeRange = .init(rawValue: 13)
        public static let nKo:                                     UnicodeRange = .init(rawValue: 14)
        public static let devangari:                               UnicodeRange = .init(rawValue: 15)
        public static let bengali:                                 UnicodeRange = .init(rawValue: 16)
        public static let gurmukhi:                                UnicodeRange = .init(rawValue: 17)
        public static let gujarati:                                UnicodeRange = .init(rawValue: 18)
        public static let oriya:                                   UnicodeRange = .init(rawValue: 19)
        public static let tamil:                                   UnicodeRange = .init(rawValue: 20)
        public static let telegu:                                  UnicodeRange = .init(rawValue: 21)
        public static let kannada:                                 UnicodeRange = .init(rawValue: 22)
        public static let malayalam:                               UnicodeRange = .init(rawValue: 23)
        public static let thai:                                    UnicodeRange = .init(rawValue: 24)
        public static let lao:                                     UnicodeRange = .init(rawValue: 25)
        public static let georgian:                                UnicodeRange = .init(rawValue: 26)
        public static let balinese:                                UnicodeRange = .init(rawValue: 27)
        public static let hangulJamo:                              UnicodeRange = .init(rawValue: 28)
        public static let latinExtended:                           UnicodeRange = .init(rawValue: 29)
        public static let greekExtended:                           UnicodeRange = .init(rawValue: 30)
        public static let generalPunctuation:                      UnicodeRange = .init(rawValue: 31)
        public static let superscriptsAndSubscripts:               UnicodeRange = .init(rawValue: 32)
        public static let currencySymbols:                         UnicodeRange = .init(rawValue: 33)
        public static let combiningDiacriticalMarksForSymbols:     UnicodeRange = .init(rawValue: 34)
        public static let letterlikeSymbols:                       UnicodeRange = .init(rawValue: 35)
        public static let numberForms:                             UnicodeRange = .init(rawValue: 36)
        public static let arrows:                                  UnicodeRange = .init(rawValue: 37)
        public static let mathematicalOperators:                   UnicodeRange = .init(rawValue: 38)
        public static let miscTechnical:                           UnicodeRange = .init(rawValue: 39)
        public static let controlPictures:                         UnicodeRange = .init(rawValue: 40)
        public static let ocr:                                     UnicodeRange = .init(rawValue: 41)
        public static let enclosedAlphanumerics:                   UnicodeRange = .init(rawValue: 42)
        public static let boxDrawing:                              UnicodeRange = .init(rawValue: 43)
        public static let blockElements:                           UnicodeRange = .init(rawValue: 44)
        public static let geometricShapes:                         UnicodeRange = .init(rawValue: 45)
        public static let miscSymbols:                             UnicodeRange = .init(rawValue: 46)
        public static let dingbats:                                UnicodeRange = .init(rawValue: 47)
        public static let cjkSymbolsAndPunctuation:                UnicodeRange = .init(rawValue: 48)
        public static let hiragana:                                UnicodeRange = .init(rawValue: 49)
        public static let katakana:                                UnicodeRange = .init(rawValue: 50)
        public static let bopomofo:                                UnicodeRange = .init(rawValue: 51)
        public static let hangulCompatibilityJamo:                 UnicodeRange = .init(rawValue: 52)
        public static let phagsPa:                                 UnicodeRange = .init(rawValue: 53)
        public static let enclosedCJKLettersAndMonths:             UnicodeRange = .init(rawValue: 54)
        public static let cjkCompatibility:                        UnicodeRange = .init(rawValue: 55)
        public static let hangulSyllables:                         UnicodeRange = .init(rawValue: 56)
        public static let nonPlane0:                               UnicodeRange = .init(rawValue: 57)
        public static let phoenician:                              UnicodeRange = .init(rawValue: 58)
        public static let cjkUnifiedIdeographs:                    UnicodeRange = .init(rawValue: 59)
        public static let privateUseAreaPlane0:                    UnicodeRange = .init(rawValue: 60)
        public static let cjkStrokesAndCompatibilityIdeographs:    UnicodeRange = .init(rawValue: 61)
        public static let alphabeticPresentationForms:             UnicodeRange = .init(rawValue: 62)
        public static let arabicPresentationFormsA:                UnicodeRange = .init(rawValue: 63)
        public static let combiningHalfMarks:                      UnicodeRange = .init(rawValue: 64)
        public static let verticalAndCJKCompatabilityForms:        UnicodeRange = .init(rawValue: 65)
        public static let smallFormVariants:                       UnicodeRange = .init(rawValue: 66)
        public static let arabicPresentationFormsB:                UnicodeRange = .init(rawValue: 67)
        public static let halfwidthAndFullwidthForms:              UnicodeRange = .init(rawValue: 68)
        public static let specials:                                UnicodeRange = .init(rawValue: 69)
        public static let tibetan:                                 UnicodeRange = .init(rawValue: 70)
        public static let syriac:                                  UnicodeRange = .init(rawValue: 71)
        public static let thaana:                                  UnicodeRange = .init(rawValue: 72)
        public static let sinhala:                                 UnicodeRange = .init(rawValue: 73)
        public static let myanmar:                                 UnicodeRange = .init(rawValue: 74)
        public static let ethiopic:                                UnicodeRange = .init(rawValue: 75)
        public static let cherokee:                                UnicodeRange = .init(rawValue: 76)
        public static let unitedCanadianAboriginalSyllabics:       UnicodeRange = .init(rawValue: 77)
        public static let ogham:                                   UnicodeRange = .init(rawValue: 78)
        public static let runic:                                   UnicodeRange = .init(rawValue: 79)
        public static let khmer:                                   UnicodeRange = .init(rawValue: 80)
        public static let mongolian:                               UnicodeRange = .init(rawValue: 81)
        public static let braillePatterns:                         UnicodeRange = .init(rawValue: 82)
        public static let yi:                                      UnicodeRange = .init(rawValue: 83)
        public static let tagalogHanunooBuhidTagbanwa:             UnicodeRange = .init(rawValue: 84)
        public static let oldItalic:                               UnicodeRange = .init(rawValue: 85)
        public static let gothic:                                  UnicodeRange = .init(rawValue: 86)
        public static let deseret:                                 UnicodeRange = .init(rawValue: 87)
        public static let musicalSymbols:                          UnicodeRange = .init(rawValue: 88)
        public static let mathematicalAlphanumericSymbols:         UnicodeRange = .init(rawValue: 89)
        public static let privateUsePlanes15_16:                   UnicodeRange = .init(rawValue: 90)
        public static let variationSelectors:                      UnicodeRange = .init(rawValue: 91)
        public static let tags:                                    UnicodeRange = .init(rawValue: 92)
        public static let limbu:                                   UnicodeRange = .init(rawValue: 93)
        public static let taiLe:                                   UnicodeRange = .init(rawValue: 94)
        public static let newTaiLue:                               UnicodeRange = .init(rawValue: 95)
        public static let buginese:                                UnicodeRange = .init(rawValue: 96)
        public static let glagolitic:                              UnicodeRange = .init(rawValue: 97)
        public static let tifinagh:                                UnicodeRange = .init(rawValue: 98)
        public static let yijingHexagramSymbols:                   UnicodeRange = .init(rawValue: 99)
        public static let sylotiNagri:                             UnicodeRange = .init(rawValue: 100)
        public static let linearB:                                 UnicodeRange = .init(rawValue: 101)
        public static let ancientGreekNumbers:                     UnicodeRange = .init(rawValue: 102)
        public static let ugaritic:                                UnicodeRange = .init(rawValue: 103)
        public static let oldPersian:                              UnicodeRange = .init(rawValue: 104)
        public static let shavian:                                 UnicodeRange = .init(rawValue: 105)
        public static let osmanya:                                 UnicodeRange = .init(rawValue: 106)
        public static let cypriotSyllabary:                        UnicodeRange = .init(rawValue: 107)
        public static let kharoshthi:                              UnicodeRange = .init(rawValue: 108)
        public static let taiXuanJingSymbols:                      UnicodeRange = .init(rawValue: 109)
        public static let cuneiform:                               UnicodeRange = .init(rawValue: 110)
        public static let countingRodNumerals:                     UnicodeRange = .init(rawValue: 111)
        public static let sundanese:                               UnicodeRange = .init(rawValue: 112)
        public static let lepcha:                                  UnicodeRange = .init(rawValue: 113)
        public static let olChiki:                                 UnicodeRange = .init(rawValue: 114)
        public static let saurashtra:                              UnicodeRange = .init(rawValue: 115)
        public static let kayahLi:                                 UnicodeRange = .init(rawValue: 116)
        public static let rejang:                                  UnicodeRange = .init(rawValue: 117)
        public static let cham:                                    UnicodeRange = .init(rawValue: 118)
        public static let ancientSymbols:                          UnicodeRange = .init(rawValue: 119)
        public static let phaistosDisc:                            UnicodeRange = .init(rawValue: 120)
        public static let carianLycianLydian:                      UnicodeRange = .init(rawValue: 121)
        public static let dominoAndMahjongTiles:                   UnicodeRange = .init(rawValue: 122)
        public static let none                                                  = Int.max
    }

    struct UnicodeMask1: OptionSet {
        public let rawValue: UInt32
        public init(rawValue: UInt32) {
            self.rawValue = rawValue
        }
        public static let basicLatin:                              UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.basicLatin.rawValue)
        public static let latin1Supplement:                        UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.latin1Supplement.rawValue)
        public static let latinExtendedA:                          UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.latinExtendedA.rawValue)
        public static let latinExtendedB:                          UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.latinExtendedB.rawValue)
        public static let ipaPhoneticExtensions:                   UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.ipaPhoneticExtensions.rawValue)
        public static let spacingModifierLetters:                  UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.spacingModifierLetters.rawValue)
        public static let combiningDiacriticalMarks:               UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.combiningDiacriticalMarks.rawValue)
        public static let greekAndCoptic:                          UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.greekAndCoptic.rawValue)
        public static let coptic:                                  UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.coptic.rawValue)
        public static let cyrillic:                                UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.cyrillic.rawValue)
        public static let armenian:                                UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.armenian.rawValue)
        public static let hebrew:                                  UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.hebrew.rawValue)
        public static let vai:                                     UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.vai.rawValue)
        public static let arabic:                                  UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.arabic.rawValue)
        public static let nKo:                                     UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.nKo.rawValue)
        public static let devangari:                               UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.devangari.rawValue)
        public static let bengali:                                 UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.bengali.rawValue)
        public static let gurmukhi:                                UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.gurmukhi.rawValue)
        public static let gujarati:                                UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.gujarati.rawValue)
        public static let oriya:                                   UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.oriya.rawValue)
        public static let tamil:                                   UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.tamil.rawValue)
        public static let telegu:                                  UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.telegu.rawValue)
        public static let kannada:                                 UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.kannada.rawValue)
        public static let malayalam:                               UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.malayalam.rawValue)
        public static let thai:                                    UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.thai.rawValue)
        public static let lao:                                     UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.lao.rawValue)
        public static let georgian:                                UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.georgian.rawValue)
        public static let balinese:                                UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.balinese.rawValue)
        public static let hangulJamo:                              UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.hangulJamo.rawValue)
        public static let latinExtended:                           UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.latinExtended.rawValue)
        public static let greekExtended:                           UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.greekExtended.rawValue)
        public static let generalPunctuation:                      UnicodeMask1 = .init(rawValue: 1 << UnicodeRange.generalPunctuation.rawValue)
    }

    struct UnicodeMask2: OptionSet {
        public let rawValue: UInt32
        public init(rawValue: UInt32) {
            self.rawValue = rawValue
        }
        public static let superscriptsAndSubscripts:               UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.superscriptsAndSubscripts.rawValue % 32))
        public static let currencySymbols:                         UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.currencySymbols.rawValue % 32))
        public static let combiningDiacriticalMarksForSymbols:     UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.combiningDiacriticalMarksForSymbols.rawValue % 32))
        public static let letterlikeSymbols:                       UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.letterlikeSymbols.rawValue % 32))
        public static let numberForms:                             UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.numberForms.rawValue % 32))
        public static let arrows:                                  UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.arrows.rawValue % 32))
        public static let mathematicalOperators:                   UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.mathematicalOperators.rawValue % 32))
        public static let miscTechnical:                           UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.miscTechnical.rawValue % 32))
        public static let controlPictures:                         UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.controlPictures.rawValue % 32))
        public static let ocr:                                     UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.ocr.rawValue % 32))
        public static let enclosedAlphanumerics:                   UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.enclosedAlphanumerics.rawValue % 32))
        public static let boxDrawing:                              UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.boxDrawing.rawValue % 32))
        public static let blockElements:                           UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.blockElements.rawValue % 32))
        public static let geometricShapes:                         UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.geometricShapes.rawValue % 32))
        public static let miscSymbols:                             UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.miscSymbols.rawValue % 32))
        public static let dingbats:                                UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.dingbats.rawValue % 32))
        public static let cjkSymbolsAndPunctuation:                UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.cjkSymbolsAndPunctuation.rawValue % 32))
        public static let hiragana:                                UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.hiragana.rawValue % 32))
        public static let katakana:                                UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.katakana.rawValue % 32))
        public static let bopomofo:                                UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.bopomofo.rawValue % 32))
        public static let hangulCompatibilityJamo:                 UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.hangulCompatibilityJamo.rawValue % 32))
        public static let phagsPa:                                 UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.phagsPa.rawValue % 32))
        public static let enclosedCJKLettersAndMonths:             UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.enclosedCJKLettersAndMonths.rawValue % 32))
        public static let cjkCompatibility:                        UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.cjkCompatibility.rawValue % 32))
        public static let hangulSyllables:                         UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.hangulSyllables.rawValue % 32))
        public static let nonPlane0:                               UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.nonPlane0.rawValue % 32))
        public static let phoenician:                              UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.phoenician.rawValue % 32))
        public static let cjkUnifiedIdeographs:                    UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.cjkUnifiedIdeographs.rawValue % 32))
        public static let privateUseAreaPlane0:                    UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.privateUseAreaPlane0.rawValue % 32))
        public static let cjkStrokesAndCompatibilityIdeographs:    UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.cjkStrokesAndCompatibilityIdeographs.rawValue % 32))
        public static let alphabeticPresentationForms:             UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.alphabeticPresentationForms.rawValue % 32))
        public static let arabicPresentationFormsA:                UnicodeMask2 = .init(rawValue: 1 << (UnicodeRange.arabicPresentationFormsA.rawValue % 32))

    }

    struct UnicodeMask3: OptionSet {
        public let rawValue: UInt32
        public init(rawValue: UInt32) {
            self.rawValue = rawValue
        }
        public static let combiningHalfMarks:                  UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.combiningHalfMarks.rawValue % 32))
        public static let verticalAndCJKCompatabilityForms:    UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.verticalAndCJKCompatabilityForms.rawValue % 32))
        public static let smallFormVariants:                   UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.smallFormVariants.rawValue % 32))
        public static let arabicPresentationFormsB:            UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.arabicPresentationFormsB.rawValue % 32))
        public static let halfwidthAndFullwidthForms:          UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.halfwidthAndFullwidthForms.rawValue % 32))
        public static let specials:                            UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.specials.rawValue % 32))
        public static let tibetan:                             UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.tibetan.rawValue % 32))
        public static let syriac:                              UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.syriac.rawValue % 32))
        public static let thaana:                              UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.thaana.rawValue % 32))
        public static let sinhala:                             UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.sinhala.rawValue % 32))
        public static let myanmar:                             UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.myanmar.rawValue % 32))
        public static let ethiopic:                            UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.ethiopic.rawValue % 32))
        public static let cherokee:                            UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.cherokee.rawValue % 32))
        public static let unitedCanadianAboriginalSyllabics:   UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.unitedCanadianAboriginalSyllabics.rawValue % 32))
        public static let ogham:                               UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.ogham.rawValue % 32))
        public static let runic:                               UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.runic.rawValue % 32))
        public static let khmer:                               UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.khmer.rawValue % 32))
        public static let mongolian:                           UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.mongolian.rawValue % 32))
        public static let braillePatterns:                     UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.braillePatterns.rawValue % 32))
        public static let yi:                                  UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.yi.rawValue % 32))
        public static let tagalogHanunooBuhidTagbanwa:         UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.tagalogHanunooBuhidTagbanwa.rawValue % 32))
        public static let oldItalic:                           UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.oldItalic.rawValue % 32))
        public static let gothic:                              UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.gothic.rawValue % 32))
        public static let deseret:                             UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.deseret.rawValue % 32))
        public static let musicalSymbols:                      UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.musicalSymbols.rawValue % 32))
        public static let mathematicalAlphanumericSymbols:     UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.mathematicalAlphanumericSymbols.rawValue % 32))
        public static let privateUsePlanes15_16:               UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.privateUsePlanes15_16.rawValue % 32))
        public static let variationSelectors:                  UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.variationSelectors.rawValue % 32))
        public static let tags:                                UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.tags.rawValue % 32))
        public static let limbu:                               UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.limbu.rawValue % 32))
        public static let taiLe:                               UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.taiLe.rawValue % 32))
        public static let newTaiLue:                           UnicodeMask3 = .init(rawValue: 1 << (UnicodeRange.newTaiLue.rawValue % 32))
    }

    struct UnicodeMask4: OptionSet {
        public let rawValue: UInt32
        public init(rawValue: UInt32) {
            self.rawValue = rawValue
        }
        public static let buginese:                            UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.buginese.rawValue % 32))
        public static let glagolitic:                          UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.glagolitic.rawValue % 32))
        public static let tifinagh:                            UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.tifinagh.rawValue % 32))
        public static let yijingHexagramSymbols:               UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.yijingHexagramSymbols.rawValue % 32))
        public static let sylotiNagri:                         UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.sylotiNagri.rawValue % 32))
        public static let linearB:                             UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.linearB.rawValue % 32))
        public static let ancientGreekNumbers:                 UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.ancientGreekNumbers.rawValue % 32))
        public static let ugaritic:                            UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.ugaritic.rawValue % 32))
        public static let oldPersian:                          UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.oldPersian.rawValue % 32))
        public static let shavian:                             UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.shavian.rawValue % 32))
        public static let osmanya:                             UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.osmanya.rawValue % 32))
        public static let cypriotSyllabary:                    UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.cypriotSyllabary.rawValue % 32))
        public static let kharoshthi:                          UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.kharoshthi.rawValue % 32))
        public static let taiXuanJingSymbols:                  UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.taiXuanJingSymbols.rawValue % 32))
        public static let cuneiform:                           UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.cuneiform.rawValue % 32))
        public static let countingRodNumerals:                 UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.countingRodNumerals.rawValue % 32))
        public static let sundanese:                           UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.sundanese.rawValue % 32))
        public static let lepcha:                              UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.lepcha.rawValue % 32))
        public static let olChiki:                             UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.olChiki.rawValue % 32))
        public static let saurashtra:                          UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.saurashtra.rawValue % 32))
        public static let kayahLi:                             UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.kayahLi.rawValue % 32))
        public static let rejang:                              UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.rejang.rawValue % 32))
        public static let cham:                                UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.cham.rawValue % 32))
        public static let ancientSymbols:                      UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.ancientSymbols.rawValue % 32))
        public static let phaistosDisc:                        UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.phaistosDisc.rawValue % 32))
        public static let carianLycianLydian:                  UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.carianLycianLydian.rawValue % 32))
        public static let dominoAndMahjongTiles:               UnicodeMask4 = .init(rawValue: 1 << (UnicodeRange.dominoAndMahjongTiles.rawValue % 32))
    }
}
